### ISSUE TITLE
Exception "Some required arguments are not valid" thrown when output of a function is translated

### ISSUE THREAD

**Issue by mjrider** [php-gettext/PHP-Scanner#3]
adding to `tests/assets/code.php` will trigger this case:
```php
__(ucfirst('test'));
```

While it seems logical that the scanner can't index this line, a warning/notice is a lot better.
Because this exception is not catched internally, it's impossible to ignore it and continue the rest of the file, we add the translations like this manually to the translation file. This works in the previous version of php-gettext

**Comment by oscarotero** [comment]
I don't know why you want to have gettext functions in your code that cannot be extracted. Anyway, I could add an option to ignore these functions instead throw an exception.

**Comment by mjrider** [comment]
The strings in this case are coming from a DB and the translations are sourced from an other place.
99% of all translations in this project are just plain strings, just a few where the text is sourced from a db.

And yes a flag to skip over invalid translations would be nice

**Comment by oscarotero** [comment]
Ok, the PHPScanner class extends CodeScanner class, that is provided by gettext/gettext, so I've had to release [a new version of gettext/gettext](https://github.com/php-gettext/Gettext/blob/v5.1.0/CHANGELOG.md) with this option. From now, any other code scanner (like JsScanner) has this feature too.

Simply update gettext/gettext to 5.1 and configure the scanner with `$scanner->ignoreInvalidFunctions()`
