### ISSUE TITLE
Twig scanner?

### ISSUE THREAD

**Issue by maicol07** [php-gettext/PHP-Scanner#7]
Hi,
is there a Twig scanner or does PHP scanner works as well with Twig? How?
Thanks

**Comment by oscarotero** [comment]
Gettext v4 has twig scanner: https://github.com/php-gettext/Gettext/tree/4.x

**Comment by maicol07** [comment]
@oscarotero what about v5?

**Comment by oscarotero** [comment]
V5 has not a twig scanner at this moment. Maybe in the future, but don't know when.

**Comment by oscarotero** [comment]
There's a work in progress repository to implement a scanner for twig templates: https://github.com/php-gettext/Twig-Scanner
