### ISSUE TITLE
Comment extraction not working in certain cases

### ISSUE THREAD

**Issue by lbarbula** [php-gettext/PHP-Scanner#8]
Trying to leverage the comment extraction functionality of the PhpScanner class. I am having a hard time getting anything except in the simplest of cases.  
Working:
```
//Translators: foo
gettext('bar');
//Translators: bar
echo gettext('foo');
```

Not Working:
```
//Translators: foo
$foo = gettext('foo');
//Translators: bar
$bar = sprintf(_('bar %s', 'foo'));
```

**Comment by oscarotero** [comment]
I just commited some changes to include comments from variable assigments. Could you test it?
Thanks

**Comment by lbarbula** [comment]
@oscarotero I'm running into some issues in testing. Do I need a feature branch for the gettext library checked out for this to function as expected?

**Comment by lbarbula** [comment]
@oscarotero that seems to do the trick!

**Comment by lbarbula** [comment]
Do you have an estimation on the next release with these updates?

**Comment by oscarotero** [comment]
Yes, it's already released: https://github.com/php-gettext/PHP-Scanner/releases/tag/v1.2.0 😄

**Comment by lbarbula** [comment]
You are worth your weight in gold, thank you very much!
